### ISSUE TITLE
Fill/Padd binary

### ISSUE THREAD

**Issue by Zardoz89** [techcompliant/DASM#8]
DASM actually can't fill whit 0s were the source code uses "org" to emplace data or function on a non contiguous way.

For example : 

```
org 0
.dat 0xDEAD

org 0x1FF
.dat 0xBEEF
```

Results on a file of 4 bytes with 0xDEAD , 0xBEEF, instead of filling addresses 0x1 to 0x1FE with 0x0000

DASM should allow emplace code/data at arbitrary addresses and fill the output file on some way. It helps a lot to create bootable disks directly from DASM, and there is other situations were this behaviour is desired. Perhaps a switch to toggle this "absolute emplace" could be desirable.

**Comment by eva-knight** [comment]
This switch exists - it's the ARRANGECHUNKS flag, but is off by default. If you use FLAG ARRANGECHUNKS, 1 it should work :)

**Comment by Zardoz89** [comment]
Documentation, documentation -> https://github.com/techcompliant/DASM/wiki/Macros
